export {CarbonIcon} from './carbonBook';
export {CartIcon} from './cartIcon';
export {CrookedArrowIcon} from './crookedArrow';
export {FacebookIcon} from './facebookIcon';
export {HeartIcon} from './heartIcon';
export {InstagramIcon} from './instagramIcon'
export {MessageIcon} from './messageIcon';
export {PhoneIcon} from './phoneIcon';
export {SearchIcon} from './searchIcon';
export {WinsIcon} from './winsIcon';
export {YoutubeIcon} from './youtubeIcon';